'use strict';
const assert=require('node:assert/strict'),L=require('../docs/ledger-v02.js');
let passed=0;
function test(name,fn){fn();passed++;console.log('PASS',name);}
const movie=id=>({id,title:`Film ${id}`,url:'https://www.justwatch.com/pl/film/example',genres:[],offers:[]});
const session=()=>({id:'one',startedAt:'2026-09-18T20:00:00Z',elapsedMs:10000,events:[],baseCompleted:0,completeData:true});
const s=session();s.events=[{type:'pick',winner:'A',loser:'B'},{type:'pick',winner:'A',loser:'C'}];
const g={completed:2,champion:'A'};
test('New session has no fictitious actions',()=>assert.equal(L.create().events.length,0));
test('Session ids are distinct',()=>assert.notEqual(L.create().id,L.create().id));
test('Decisions are actual completed comparisons',()=>assert.equal(L.summary(s,g).decisions,2));
test('Distinct defeated opponents',()=>assert.equal(L.summary(s,g).defeated,2));
test('Duplicate opponent does not inflate statistics',()=>{const x=L.copy(s);x.events.push(x.events[0]);assert.equal(L.summary(x,g).defeated,2);});
test('No record for a merely leftover candidate',()=>assert.equal(L.result(session(),{completed:0,champion:'A'},movie('A'),[],'date'),null));
test('Explicit acceptance can record a leftover',()=>{const x=session();x.events.push({type:'accept',winner:'A'});assert.equal(L.result(x,{completed:0,champion:'A'},movie('A'),[],'date').stats.decisions,0);});
test('A result is neither opened nor watched',()=>{const r=L.result(s,g,movie('A'),[],'date');assert.equal(r.openedAt,null);assert.equal(r.watchedAt,null);});
test('Result is a deep copy',()=>{const r=L.result(s,g,movie('A'),[],'date');r.events[0].winner='other';assert.equal(s.events[0].winner,'A');});
test('Same session updates instead of duplicates',()=>{const r=L.result(s,g,movie('A'),[],'date');assert.equal(L.upsert([r],r).length,1);});
test('Same winner preserves watched state and rating',()=>{const r=L.result(s,g,movie('A'),[],'date');r.watchedAt='today';r.openedAt='now';r.score=4;const n=L.upsert([r],L.result(s,g,movie('A'),[],'date'))[0];assert.equal(n.score,4);assert.equal(n.watchedAt,'today');});
test('Different winner cannot inherit the previous rating',()=>{const r=L.result(s,g,movie('A'),[],'date');r.score=4;const x=L.copy(s);x.events.push({type:'pick',winner:'B',loser:'A'});const n=L.upsert([r],L.result(x,{completed:3,champion:'B'},movie('B'),[],'date'))[0];assert.equal(n.score,null);});
test('History is bounded at 200 sessions',()=>{const r=L.result(s,g,movie('A'),[],'date');assert.equal(L.upsert(Array.from({length:210},(_,i)=>({...r,id:`old${i}`})),r).length,200);});
test('Average excludes incomplete legacy measurements',()=>{const r=L.result(s,g,movie('A'),[],'date');const x=L.copy(r);x.stats.measured=false;x.stats.elapsedMs=99999;assert.equal(L.aggregate([r,x]).averageMs,10000);});
test('No invented average for empty history',()=>assert.equal(L.aggregate([]).averageMs,null));
test('Opening a platform does not change watched count',()=>{const r=L.result(s,g,movie('A'),[],'date');r.openedAt='now';assert.equal(L.aggregate([r]).watched,0);assert.equal(L.aggregate([r]).opened,1);});
test('Legacy session counts only newly measured decisions',()=>{const x=session();x.baseCompleted=7;x.completeData=false;assert.equal(L.summary(x,{completed:9,champion:'A'}).decisions,2);assert.equal(L.summary(x,g).measured,false);});
test('Negative time is clamped',()=>{const x=session();x.elapsedMs=-20;assert.equal(L.summary(x,g).elapsedMs,0);});
test('Skip and seen have distinct counters',()=>{const x=session();x.events=[{type:'skip'},{type:'seen'}];const a=L.summary(x,{completed:0,champion:null});assert.equal(a.decisions,0);assert.equal(a.skippedPairs,1);assert.equal(a.markedSeen,1);});
test('Polish plural forms',()=>{for(const [n,w] of [[1,'a'],[2,'b'],[4,'b'],[5,'c'],[12,'c'],[22,'b'],[112,'c']])assert.equal(L.plural(n,'a','b','c'),w);});
test('Duration formatting and unknown value',()=>{assert.equal(L.duration(102000),'1 min 42 s');assert.equal(L.duration(null),'—');});
console.log(JSON.stringify({suite:'ledger',passed,failed:0}));
