import { test } from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import { makeHandler } from '../supabase/functions/_shared/room-handler.mjs';
import {memoryStore} from './room-test-store.mjs';
const origin='https://seans.example.test',A=randomUUID(),B=randomUUID(),C=randomUUID(),invite='f'.repeat(64),ids=Array.from({length:26},(_,i)=>'tm'+i);
function fixture(){const store=memoryStore(),handler=makeHandler({store,allowedOrigins:[origin],authenticate:async s=>[A,B,C].includes(s.slice(7))?s.slice(7):null});
const send=async(user,body,otherOrigin=origin)=>{const r=await handler(new Request(origin,{method:'POST',headers:{origin:otherOrigin,authorization:'Bearer '+user,'content-type':'application/json'},body:typeof body==='string'?body:JSON.stringify(body)}));return {status:r.status,body:await r.json(),headers:r.headers};};
return {store,handler,send,async create(){const roomId=randomUUID();return {roomId,reply:await send(A,{action:'create',roomId,invite,ids,services:['netflix'],catalogueAt:new Date().toISOString()})};}};}
test('Unauthenticated room API request is rejected',async()=>{const f=fixture();assert.equal((await f.send('invalid',{})).status,401);});
test('Unapproved origin cannot use the API',async()=>{const f=fixture();assert.equal((await f.send(A,{},'https://attacker.test')).status,403);});
test('Malformed and oversized JSON rejected',async()=>{const f=fixture();assert.equal((await f.send(A,'{')).status,400);assert.equal((await f.send(A,'a'.repeat(13000))).status,413);});
test('POST reply has no-store and nosniff',async()=>{const f=fixture(),{reply}=await f.create();assert.equal(reply.headers.get('cache-control'),'no-store');assert.equal(reply.headers.get('x-content-type-options'),'nosniff');});
test('Create is idempotent after a lost response',async()=>{const f=fixture(),{roomId,reply}=await f.create();const again=await f.send(A,{action:'create',roomId,invite,ids,services:['netflix'],catalogueAt:new Date().toISOString()});assert.equal(again.status,200);assert.deepEqual(reply.body,again.body);assert.equal(f.store.rows.size,1);});
test('Simultaneous guest joins cannot create a third seat',async()=>{const f=fixture(),{roomId}=await f.create();const replies=await Promise.all([B,C].map(u=>f.send(u,{action:'join',roomId,invite})));assert.equal(replies.filter(r=>r.status===200).length,1);assert.equal(f.store.rows.size,1);});
test('Two simultaneous votes from different participants are both retained',async()=>{const f=fixture(),{roomId}=await f.create();await f.send(B,{action:'join',roomId,invite});const [a,b]=await Promise.all([A,B].map(u=>f.send(u,{action:'read',roomId})));const votes=await Promise.all([a,b].map((r,i)=>f.send(i?B:A,{action:'command',roomId,command:{type:'pick',filmId:r.body.room.self.pair[0],seq:r.body.room.self.seq,round:1,opId:randomUUID()}})));assert.ok(votes.every(r=>r.status===200));const actual=await f.store.get(roomId);assert.equal(actual.players.a.decisions,1);assert.equal(actual.players.b.decisions,1);});
test('Guessing a room UUID does not disclose votes',async()=>{const f=fixture(),{roomId}=await f.create();const r=await f.send(C,{action:'read',roomId});assert.equal(r.status,404);assert.deepEqual(Object.keys(r.body),['error']);});
test('Raw invitation secret is not stored or returned by API',async()=>{const f=fixture(),{roomId,reply}=await f.create();assert.ok(!JSON.stringify(reply.body).includes(invite));assert.ok(!JSON.stringify(await f.store.get(roomId)).includes(invite));});
test('Database errors do not disclose credentials or SQL',async()=>{const f=fixture();f.store.get=async()=>{throw Error('postgres://secret');};const r=await f.send(A,{action:'read',roomId:randomUUID()});assert.equal(r.status,503);assert.equal(JSON.stringify(r.body).includes('secret'),false);});
